= Homework Assignments
Information Systems Design

This is your private repository 
for working and submitting 
homework assignments.

Each homework assignment is stored in a separate folder
within this repository.

== Getting Started

To get started, you will clone your Github repository
to your _sandbox_
on your CSE share.

Follow these steps:

. Run PyCharm
. From the *Welcome to PyCharm* window, click *Check out from Version Control*
. Click *Github*
. Fill out the following details:
.. For *Git Repository URL*, enter
   `https://github.com/tu-isd/<your-github-id>-homework.git`
   except substitute your actual Github ID for `<your-github-id>`
.. For *Parent Directory* and *Directory Name*, 
   choose a sensible location on your CSE share.
. Click the *Clone* button.

These steps should create a new PyCharm project
that contains starter files for the ISD homework assignments.

== Installing Python Modules (Automated Process)

For both individual homework assignments and the project,
you will have to install Python modules in addition to those
installed by default.

For example, say you want to use Flask.
Your Python code would include in `import` statement like this:
[source,python]
----
from flask import Flask
----
If Flask is not yet installed, PyCharm will show a squiggly underline below `flask`
to indicate that it doesn't know about this module.

As pointed out by Caleb Dinsmore (thank you!),
PyCharm is incredibly helpful when you need a new module.

. Click to place your cursor on `flask` in the `import` statement, and hit *Alt+Enter*.
  This will open up a suggestions menu for resolving the error.
  The first suggestion should be `Install package <package-name>`.
. Select the `Install package` option.
  PyCharm will install the package.
  You'll see a progress bar at the bottom of the PyCharm window as the installation completes.

== Installing Python Modules (Manual Process)

If the automatic process for module installation doesn't work,
here are detailed manual instructions for installing a module.

. Run PyCharm
. Open PyCharm's setttings, which are found under different menus depending on your computer.
** On a Mac, from the *PyCharm* menu, choose *Preferences...*
** On Windows, from the *File* menu, choose *Settings...*
. In the list on the left, find the *Project* section.
** If *Project Interpreter* _is_ shown beneath *Project*, click on *Project Interpreter*
** If *Project Interpreter* is _not_ show beneath *Project*, either:
*** Click the triangle to the left of *Project*, then click on *Project Interpreter*
*** Click on *Project*, the click on *Project Interpreter* in the main section of the window.
. The *Project Interpreter* window shows a list of packages currently installed.
  Check that the package you need isn't already installed. If it is, you're done--click *Cancel*.
. Click the *+* button at the bottom of the package list.
  A window containing available packages appears.
. In the search box at the top of the *Available Packages* window,
  type (a portion of) the name of the package you want to install.
  For example, to install Flask, type `Flask`.
. Many packages have related names.
  For example, there are a lot of packages that extend Flask that are named `Flask-<something>`.
  Make sure the correct package name is selected in the list on the left.
. Click *Install Package* at the bottom of the window.
. While the package installs, you'll see `(Installing)` next to the package name.
  When installation is complete, a message highlighted in green
  tells you that the package was installed correctly.
. Close the *Available Packages* window.
  (Unless you want to install more packages; in that case, search for the next package and repeat.)
. Check that the list of installed packages includes the package you just installed.
. Click *OK* to dismiss the settings window.

== Working on an Assignment

Following are general instructions for all assignments.

=== Update your Sandbox

Before working on an assignment,
update your sandbox from Github
to make sure you have the latest-and-greatest
version of the files for the assignment.
Do this as follows within PyCharm:

. From the *VCS* menu, choose *Update Project...*
. From the *Update Project* window,
leave the default options selected and click *OK*.

=== Instructions

Instructions for the assignment are found in a file
called `README.adoc` at the top level of each folder.
The `README.adoc` file 
(an `asciidoc` file)
should be legible as is,
but if you would like to read a nicely formatted version,
refer to the file on Github,
which formats `.adoc` files automatically as HTML.

You are welcome to use any starter files in the homework directory
to get going on the assignment.

== Submitting an Assignment

When you've completed an assignment,
you'll need to push your updated repository
back to Github, where your work
will be available for grading.

=== Add New Files

If you created any new files while working
on the assignment,
you'll need to add them to revision control
_before_ you push your completed assignment to Github.
To use PyCharm to check whether you have files not yet under revision control

. From the *View* menu, choose *Tool Windows* > *Version Control*.
. The *Version Control* window appears
. Choose the *Local Changes* tab.
. Check whether there are files listed as *Unversioned Files*.
. If so, and if the file(s) listed are ones that are part
of the project (and not just temporary files that you don't want to turn in),
right click on the file and choose *Add to VCS*.
This will register the file with Git
and it will be submitted when you push your changes to Github.

=== Commit and Push

Although commit and push are two separate Git operations,
PyCharm makes it easy to do both when you are ready to
submit your assignment.

Test.

. From the *VCS* menu, click *Commit Changes*.
`PyCharm` opens the *Commit Changes* dialog box.
. In the top-left window, `PyCharm` shows you
the files that are going to be committed.
Make sure there aren't any files that you _don't_ want to commit,
or files that are not listed there that you _do_ want to commit
(see above for information on how to add new files to Git).
. Write a brief commit message in the window
in the lower-left corner of the dialog box.
Commit messages are extremely valuable when working on a team project
so that you can communication (and remember!) what you've done.
*When your homework submission is ready for grading,
please start your commit message with `READY FOR GRADING`.*
. Hover over the highlighted *Commit* button in the lower-right corner.
. A pop-up menu appears. Choose *Commit and Push...*
. After the commit is complete, the *Push Commits* dialog appears.
Click *Push* to push your changes to Github.

=== Verify your Submission

Just to make sure everything you intended to submit
is available on Github,
you should log on to your Github account,
navigate to the appropriate homework folder
in your repository,
and verify that all the files you intended to submit
are present.
