= Homework Assignments
Information Systems Design

This is your private repository 
for working and submitting 
homework assignments.

Each homework assignment is stored in a separate folder
within this repository.

== Getting Started

To get started, you will clone your Github repository
to your _sandbox_
on your CSE share.

Follow these steps:

. Run `PyCharm`
. From the `Welcome to PyCharm` window, click *Check out from Version Control*
. Click *Github*
. Fill out the following details:
.. For *Git Repository URL*, enter
   `https://github.com/tu-isd/<your-github-id>-homework.git`
   except substitute your actual Github ID for `<your-github-id>`
.. For *Parent Directory* and *Directory Name*, 
   choose a sensible location on your CSE share.
. Click the *Clone* button.

These steps should create a new PyCharm project
that contains starter files for the ISD homework assignments.

== Working on an Assignment

As required, complete the assigned homework in the appropriate folder within
your repository.

=== Update your Sandbox

Before working on an assignment,
you should update your sandbox from Github
to make sure you have the latest-and-greatest
of the files for the assignment.
Do this as follows:

. From the *VCS* menu, choose *Update Project...*
. From the *Update Project* window,
leave the default options selected and click *OK*.

=== Instructions

Instructions for the assignment are found in a file
called `README.adoc` at the top level of each folder.
The `README.adoc` file should be legible as is,
but if you would like to read a nicely formatted version,
refer to the file on Github,
which formats `.adoc` files automatically as HTML.

You are welcome to use any starter files in the homework directory
to get going on the assignment.

== Submitting an Assignment

When you've completed an assignment,
you'll need to push your updated repository
back to Github where your work
will be visible for grading.

=== Add New Files

If you created any new files while working
on the assignment,
you'll need to add them to revision control
before you push your completed assignment to Github.
To check whether you have files not yet under revision control,
from the *View* menu, choose *Tool Windows* > *Version Control*.

The *Version Control* window show appear in PyCharm.
Choose the *Local Changes* tab.
Check whether there are files listed as *Unversioned Files*.
If so, and if the file(s) listed are ones that are part
of the project (and not just temporary files that you don't want to turn in),
right click on the file and choose *Add to VCS*.
This will register the file with Git
and it will be submitted when you push your changes to Github.

=== Commit and Push

Although commit and push are two separate Git operations,
PyCharm makes it easy to do both when you are ready to
submit your assignment.

. From the *VCS* menu, click *Commit Changes*.
`PyCharm` opens the *Commit Changes* dialog box.
. In the top-left window, `PyCharm` shows you
the files that are going to be committed.
Make sure there aren't any files that you _don't_ want to commit,
or files that are not listed there that you _do_ want to commit
(see above for information on how to add new files to Git).
. Write a brief commit message in the window
in the lower-left corner of the dialog box.
Commit messages are extremely valuable when working on a team project
so that you can communication (and remember!) what you've done.
. Hover over the highlighted *Commit* button in the lower-right corner.
. A pop-up menu appears. Choose *Commit and Push...*
. After the commit is complete, the *Push
