= Form Lab
Information Systems Design

IMPORTANT: This is an individual assignment.

== Review

Review the information on Flask forms found in the class samples:

* https://github.com/tu-isd/class-examples/tree/master/02a%20-%20sessions%20(simple)[Simple forms]
* https://github.com/tu-isd/class-examples/tree/master/02b%20-%20sessions%20(WT%20Forms)[WT Forms].

Take note of the following documentation:

* http://wtforms.readthedocs.io/en/latest/index.html[WT Forms]
  (generic WT Forms documentation)
** http://wtforms.readthedocs.io/en/latest/fields.html[Information on specific field types]
** http://wtforms.readthedocs.io/en/latest/validators.html[Details on validators]

* https://flask-wtf.readthedocs.io/en/stable/[Flask WT Forms]
  (Flask interface to WT Forms)
* https://getbootstrap.com/docs/4.0/components/forms[Styling forms with Bootstrap]

== Install

In your development environment,
you'll need to install `Flask-WTF`
in the same way that you installed `Flask` initially.

As a reminder if you're using PyCharm:

1. Open *Preferences* (Mac) or *File > Settings* (Windows)
1. Navigate to *Project > Project Interpreter*
1. Click the *`+`* button and search for `Flask-WTF`
1. Select `Flask-WTF` and click `Install Package`

== Construct

Construct a Flask application that conforms to the following requirements.

The application provides a new-user registration page at the URL `/register`.
The page allows the user to submit:

* First name
* Last name
* E-mail address
* Password
* Password confirmation

The application implements a view function called `register`
that can handle both a

* `GET` request that returns the initial, empty registration form
* `POST` request that processes a submitted form

Using WT Forms, the view function must apply these validations:

* First name and last name must be at least five characters in length
* E-mail address must be valid
* Password must be at least eight characters long and must contain at least one letter,
   one digit, and one punctuation character.
* Password and password confirmation fields must match exactly

If any validation criteria fail,
the application should redisplay the from
together with error information.
The error message should detail each validation failure.
For example, if the first name is too short, the password and its validation don't match,
and the e-mail address is formatted improperly,
the error message should be similar to
----
There are errors in your registration form:
* First name is too short (must be at least five characters)
* Password and confirmation don't match
* E-mail address doesn't look valid
----

When the registration form satisfies all the validation criteria:

1. Store the user information in the Flask `session` object.
2. Redirect the user to a confirmation page with url `/confirmation`
   _using browser redirection_.

The confirmation page should
include the user's first name, last name, and email address.

== Verify

. Run the develoment web server
. Test all possible validation errors detailed above.
  Be sure the proper error message(s) are displayed for each type of validation.
. Test that a form with all valid fields results in the display of the confirmation page.

== Submit

Commit your updated HTML file to Git and push it to Github.

Start your Git commit comment with `READY FOR GRADING`
in your final submission of the assignment.
