= Form Lab
Information Systems Design

IMPORTANT: This is an individual assignment.

== Review

Review the information on Flask forms found in the README file of the
https://github.com/tu-isd/examples-forms[Github examples-forms repository].

== Construct

Construct a Flask application that conforms to the following requirements.

The application provides a new-user registration page at the URL `/register`.
The page allows the user to submit:

* First name
* Last name
* E-mail address
* Password
* Password confirmation

The application implements a view function called `register`
that can handle both a

* GET request that returns the initial, empty registration form
* POST request that processes a submitted form

The view function must validate the submitted form as follows:

* First name and last name must be at least five characters in length
* E-mail address must look like a plausible e-mail address.
   A simple specification for a plausible address might be
   one or more letters, an `@` sign, one or more letters, a dot (`.`) and one or more letters.
   For example `fred@ziffle.com` would satisfy this specification,
   but the following would not: `fred`, `fred@ziffle`, `@ziffle.com`, `fred.com`.
* Password must be at least eight characters long and must contain at least one letter,
   one digit, and one punctuation character.
* Password and password confirmation fields must match exactly

If any validation criteria fail,
the application should redisplay the from
together with error information.
The error message should detail each validation failure.
For example, if the first name is too short, the password and its validation don't match,
and the e-mail address is formatted improperly,
the error message should be similar to
----
There are errors in your registration form:
* First name is too short (must be at least five characters)
* Password and confirmation don't match
* E-mail address doesn't look valid
----
Because the error information displayed to the user may consist of multiple messages,
the view function should store error messages in an array as errors are detected.
Pass this array of messages to the template,
where it should be processed using a `{% for %}` directive.

When a form satisfies all the validation criteria,
redirect the user to a confirmation page
that indicates successfull completion of the registration form.

== Verify

. Run the develoment web server
. Test all possible validation errors detailed above.
  Be sure the proper error message(s) are displayed for each type of validation.
. Test that a form with all valid fields results in the display of the confirmation page.

== Submit

Commit your updated HTML file to Git and push it to Github.

Be sure to start your commit comment with `READY FOR GRADING`
in your final submission of the assignment.
