= SQL Query Lab

IMPORTANT: This is an individual assignment.

== General Instructions

* Be sure to make use of the sample code stored in the
  https://github.com/tu-isd/examples-db[`examples-db` repository] on Github.
* All functions that access the database should be stored in the `db.py` file.
  Refer to the `examples-db` application for examples.
* HTML templates should use the supplied `base.html` template

== Create a Database

. Open the Database tool window (View -> Tool Windows -> Database)
. Click the `+` button, select Data Source -> Sqlite.
  The _Data Sources and Drivers_ window should appear.
. Enter the name for your database file in the _File_ box
  (for example `hw4-db.sqlite`).
. Click the `+` button at the right end of the _File_ box
  and navigate to the directory that contains your files for this assignment.
. Click _OK_.
  The full path to the database file should now be in the _File_ box.
. Click _OK_ to close the _Data Sources and Drivers_ window.

== Schema

Create a schema with the following database tables.
You may use the Database features of PyCharm to create them
(View menu -> Tool Windows -> Database)
or write SQL `CREATE TABLE` statements directly
(refer to the `examples-db` repository for examples).

=== Table `student`

This table contains relevant information about students
who will be going on one or more trips.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| id
| integer
| Primary key

| first_name
| string
| Required (`NOT NULL`)

| last_name
| string
| Required (`NOT NULL`)

| year
| string
| Contains one of `freshman`, `sophomore`, `junior`, or `senior`

|===

=== Table `trip`

This table contains data on available trips.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| id
| integer
| Primary key

| destination
| string
| Destination of trip (e.g., `Chiang Mai, Thailand`)

| year
| integer
| Year of trip

| semester
| string
| One of `fall`, `interterm`, `spring`, or `spring break`

|===

=== Table `student_trip`

This table is an associative table that permits
a many-to-many relatinship between students and trips.
As usual for an associative table, `student_id` and `trip_id`
should be part of a composite primary key for the table,
and are also foreign keys to the `student` and `trip` tables, respectively.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| student_id
| integer
| Part of the composite primary key, and a foreign key to the `id` field of the `student` table

| trip_id
| integer
| Part of the composite primary key, and a foreign key to the `id` field of the `trip` table

|===

== Sample Data

Create sample data as follows:

. At least three students in the `student` table
. At least two trips in the `trip` table
. At least two students per trip in the `student_trip` table.

As with schema creation,
you may use PyCharm tools to populate these tables from the "Table Editor"
in the PyCharm Database view,
or you may write SQL `INSERT` statements directly.

== Trip Page

Create a Flask web application that includes
a route (`/trips`),
view function (`trip_report`),
HTML page (`trip-report.html`),
and database function (`db.trip_report`)
that creates a page containing the details of all trips.
Trip details should be formatted as an HTML table
containing the following columns:

* Trip destination
* Trip semester
* Trip year
* Student first name
* Student last name
* Student class

The table should contain one row for each student-trip combination in the `student_trip` table.
Your database function will have to include a `SELECT` statement
that joins together properly the three tables in the database.
