= SQL Query Lab

IMPORTANT: This is an individual assignment.

== General Instructions

* Be sure to make use of the sample code stored in the
  https://github.com/tu-isd/examples-db[`examples-db` repository] on Github.
* All functions that access the database should be stored in the `db.py` file.
  Refer to the `examples-db` application for examples.
* HTML templates should use the supplied `base.html` template

== Create a Database File

The best place to store your database file for a given homework assignment
is right inside the directory for that homework in your repository
(e.g., inside `HW4 - SQL Query` or wherever).
Follow these steps:

. Open the _Database_ tool window (View -> Tool Windows -> Database)
. Click the `+` button, and select Data Source -> Sqlite.
  The _Data Sources and Drivers_ window should appear.
. Click the `+` button to the right of the _File_ box.
  In the _New Database_ window, navigate to
  the same folder in which you're working (e.g., `X:\\...\HW4 - SQL Query`).
. In the _File Name_ box at the bottom of the window,
  enter a database name (e.g., `hw4-db.sqlite`).
. Click _OK_. The full path to the database file should now be in the _File_ box.
. Click _OK_ to close the _Data Sources and Drivers_ window.

== Connect to your database from Python

Use the following code to connect to your database.

[source,python]
----
import os
DATABASE = 'test-db.sqlite'

# Connect to the database.
def connect_db():
    db_path = os.path.join(os.getcwd(), DATABASE)
    if not os.path.isfile(db_path):
        raise RuntimeError("Can't find database file '{}'".format(db_path))
    connection = sqlite3.connect(db_path)
    connection.row_factory = sqlite3.Row
    return connection
----

Be sure to update the value of the `DATABASE` variable
with whatever name you gave to the database file
in the previous section (e.g., `hw4-db.sqlite`).
Set `DATABASE` to _only_ the file name (_not_ the entire path to the database file).

This function looks for your database file
in the folder in which you're working.
This should be the folder that you selected
when you created the database file above.
If `connect_db` can't find the file,
it will raise an error.
If that happens:

* Make sure you've created the file in your homework directory.
  You should be able to see it listed with your other files in the _Project_ tool window in PyCharm.
* Make sure the value of the `DATABASE` variable matches the name of the file.

== Database Troubleshooting

Students have reported seeing the following error messages.

Unable to open the database file (out of memory)::
   Your Python code can't find the file containing your database.
   Several sources suggest that the "out of memory" is a red herring.
No such table: _xyz_:: This error could stem from several causes

* You have not created the `xyz` table yet.
  You can check to see which tables are defined in your database
  by clicking the small grey triangle to the left of the SQLite icon
  in the _Database_ tool window.
* You have misspelled the table name in your query.
* You are not properly connected to the database,
  or you are connecting to a different database file than you intend.

Most of these errors can be remedied
by ensuring that you have created a database file
in a known location
and that your Python code can find that file.
These steps are detailed in the preceding sections.

== Schema

Create a schema with the following database tables.
You may use the Database features of PyCharm to create them
(View menu -> Tool Windows -> Database)
or write SQL `CREATE TABLE` statements directly
(refer to the `examples-db` repository for examples).

=== Table `student`

This table contains relevant information about students
who will be going on one or more trips.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| id
| integer
| Primary key

| first_name
| string
| Required (`NOT NULL`)

| last_name
| string
| Required (`NOT NULL`)

| year
| string
| Contains one of `freshman`, `sophomore`, `junior`, or `senior`

|===

=== Table `trip`

This table contains data on available trips.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| id
| integer
| Primary key

| destination
| string
| Destination of trip (e.g., `Chiang Mai, Thailand`)

| year
| integer
| Year of trip

| semester
| string
| One of `fall`, `interterm`, `spring`, or `spring break`

|===

=== Table `student_trip`

This table is an associative table that permits
a many-to-many relatinship between students and trips.
As usual for an associative table, `student_id` and `trip_id`
should be part of a composite primary key for the table,
and are also foreign keys to the `student` and `trip` tables, respectively.

[cols="20m,20m,60d"]
|===
| Column | Type | Notes

| student_id
| integer
| Part of the composite primary key, and a foreign key to the `id` field of the `student` table

| trip_id
| integer
| Part of the composite primary key, and a foreign key to the `id` field of the `trip` table

|===

== Sample Data

Create sample data as follows:

. At least three students in the `student` table
. At least two trips in the `trip` table
. At least two students per trip in the `student_trip` table.

As with schema creation,
you may use PyCharm tools to populate these tables from the "Table Editor"
in the PyCharm Database view,
or you may write SQL `INSERT` statements directly.

== Trip Page

Create a Flask web application that includes
a route (`/trips`),
view function (`trip_report`),
HTML page (`trip-report.html`),
and database function (`db.trip_report`)
that creates a page containing the details of all trips.
Trip details should be formatted as an HTML table
containing the following columns:

* Trip destination
* Trip semester
* Trip year
* Student first name
* Student last name
* Student class

The table should contain one row for each student-trip combination in the `student_trip` table.
Your database function will have to include a `SELECT` statement
that joins together properly the three tables in the database.
